spring:
  # https://programmerah.com/multipartexception-failed-to-parse-multipart-servlet-request%EF%BC%9B-nested-exception-is-java-lang-runtime-42626/
  # multipart 관련 에러
  servlet:
    multipart:
      location: ./data/tmp

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  profiles:
    include:
      - aws

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://spring-practice.ctvzqmwyjimr.ap-northeast-2.rds.amazonaws.com:3306/mzgz?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul"
    username: root
    password: 12341234
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug

