cloud:
  aws:
    s3:
      bucket: postmission
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIAYKERNLQ5M7Y7E46C
      secretKey: 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
    stack:
      auto: false
